#version: '3.8'
#docker-compose v2.25.0 이상 버전부터는
#docker-compose.yaml파일의 최상단에 작성된 version : '3' 이 필요없어졌다고 한다.

#version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=7228
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=7228
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

  springboot-app:
    build: .
    container_name: springboot-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/test_database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=7228
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge
